# Intro to TensorFlow 
### always check the version of modules you import

In [3]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
print(tf.__version__)
print(np.__version__)

2.10.0
1.23.3


In [4]:
# Create tensors with tf.constants()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [6]:
# create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# dimension of vector
vector.ndim

1

In [8]:
# create a matrix
matrix = tf.constant([[10, 7],
                   [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [5., 6.]], dtype=tf.float32)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 5.,  6.]], dtype=float32)>

In [11]:
# create a tensor
tensor = tf.constant([[[10., 7.],
                       [7., 10.],
                       [5., 6.]],
                      [[10., 7.],
                       [7., 10.],
                       [5., 6.]],
                      [[10., 7.],
                       [7., 10.],
                       [5., 6.]]])
tensor

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[10.,  7.],
        [ 7., 10.],
        [ 5.,  6.]],

       [[10.,  7.],
        [ 7., 10.],
        [ 5.,  6.]],

       [[10.,  7.],
        [ 7., 10.],
        [ 5.,  6.]]], dtype=float32)>

In [12]:
tensor.ndim

3

### creating tensors with `tf.Variable`

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# indexing
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

### assignment is done using `.assign()`

In [15]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
changeable_tensor[1].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### `tf.constant()` does not support assignment

In [18]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

> 🔑 **Note:** Rarely in practice we use `tf.constant` and `tf.Variable`. However if in doubt use `tf.constant` and change it later if needed.

### creating random tensors

In [19]:
# For reproducibility we have to set seed then we get psuedo random numbers
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2)) # from normal/gaussian distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3, 2)) # from uniform distribution
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [21]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2)) # from uniform distribution
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [22]:
# Comparison operations
random_1 == random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [23]:
random_1 != random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [24]:
random_1 > random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### shuffle the order of elements in tensor
> " If we want reproducible random numbers we have to use both global and operation level seed"

In [25]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 8]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  8]], dtype=int32)>

In [26]:
not_shuffled.ndim

2

In [27]:
tf.random.set_seed(42)  # global level random seed
tf.random.shuffle(not_shuffled) # operation level random seed
# return shuffled tensor does not modify the tensor passed to it.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  8],
       [10,  7]], dtype=int32)>

In [28]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  8]], dtype=int32)>

### other ways of creating tensors

In [29]:
tf.ones(shape=(7, 10))

<tf.Tensor: shape=(7, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Converting numpy arrays into tensors

> tensors can be run on a GPU

In [31]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [32]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [33]:
B = tf.constant(numpy_A.reshape(6, 4))
B

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [34]:
C = tf.constant(numpy_A, shape=(2, 3, 4))
C

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors


| Attribute         | Meaning                                   | Code                       |
| :----:-           | :----:                                    | :----:                     |
| Shape             | The length (number of elements) of each of the <br>dimensions of a tensor.       | tensor.shape           
| Rank              | The number of tensor dimensions. A  scalar has rank 0, <br> a vector has rank 1, a matrix is rank 2, a tensor has rank n.    | tensor.ndim                |
| Axis or Dimension | A particular dimension of a tensor.       | tensor[0], tensor[:, 1]…   |
| Size              | The total number of items in the tensor.  | tf.size(tensor)            |

In [35]:
rank_4_tensor = tf.constant(np.arange(1, 121).reshape(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [36]:
rank_4_tensor = tf.constant(np.arange(1, 121), shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [37]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int64, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])>

In [38]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [39]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor))
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'int64'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 120


### Indexing tensors
#### tensors can be indexed like numpy arrays

In [40]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[21, 22],
         [26, 27]]],


       [[[61, 62],
         [66, 67]],

        [[81, 82],
         [86, 87]]]])>

In [41]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [42]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#### we can add dimension to tensors whilst keeping the same information present using using `tf.newaxis`

In [43]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to" ( rank_2_tensor[:, :, tf.newaxis] )
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [44]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # expanding dimension of the tensor shape

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [45]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

##  Manipulating tensors ( Tensor Operations )

### Basic operations
`+`, `-`, `*`, `/`

In [46]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

Since we used `tf.constant()`, the original tensor is unchanged (the addition gets done on a copy).

In [47]:
# Original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
tensor - 10, tensor * 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>)

In [49]:
# To change the original tensor
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Use TensorFlow built-in math func to speed up calculations on GPU

In [50]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [51]:
# original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix multiplication

In [52]:
print(tensor)
# tf.linalg.matmul(tensor, tensor)
tf.matmul(tensor, tensor) # in lot of the tensorflow module we skip the middle submodules

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [53]:
# matrix multiplication with Python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

### Tensor transformations
* `tf.reshape()`
* `tf.transpose()`

In [54]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [55]:
tf.reshape(Y, shape=(2, 3)) # this does not modify original tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [56]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [57]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [58]:
tf.transpose(X) # this does not modify original tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [59]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [60]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

The dot product between matrices is nothing but matrix multiplication

Matrix multiplication can be done using:
* `tf.matmul()`
* `tf.tensordot()` --> performs tensor contraction

In [61]:
tf.tensordot(tf.transpose(X), Y, axes=1) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing dtype of tensors

**Default is 32-bit precision**

In [62]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [63]:
casted_vector = tf.cast(vector, dtype=tf.float32)
casted_vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 10.], dtype=float32)>

In [64]:
casted_vector = tf.cast(vector, dtype=tf.float16)
casted_vector

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10., 10.], dtype=float16)>

## Aggregating Tensors

* min
* max
* mean
* sum

In [65]:
vector = tf.constant([-10., -7.])

In [66]:
# absolute functions
tf.abs(vector)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [67]:
vector = tf.constant(np.random.randint(0, 100, size=50))
vector

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([62,  5, 76, 98, 15, 38, 21, 65, 24, 19, 62, 81, 17, 10, 47, 11, 39,
       97, 85, 31, 19, 99, 49, 68, 94, 13, 24, 54, 99, 54, 57, 97, 29, 36,
       32, 61, 77, 54, 83, 65, 94, 48, 83, 81, 16, 73, 87, 49, 48, 62])>

In [68]:
# min, max
tf.reduce_min(vector), tf.reduce_max(vector)

(<tf.Tensor: shape=(), dtype=int64, numpy=5>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>)

In [69]:
# mean
tf.reduce_mean(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [70]:
# sum
tf.reduce_sum(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=2708>

In [71]:
tf.math.reduce_variance(tf.cast(vector, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=805.77435>

In [72]:
tf.math.reduce_std(tf.cast(vector, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.386166>

### We can use library <u>tensorflow_probability</u> to use stats functions

> `import tensorflow_probability as tfp`

In [73]:
tfp.stats.variance(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=805>

In [74]:
tfp.stats.stddev(tf.cast(vector, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.386166>

### Positional max and min

In [75]:
tf.argmax(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [76]:
vector[tf.argmax(vector)]

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [77]:
assert vector[tf.argmax(vector)] == tf.reduce_max(vector)

In [78]:
tf.argmin(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [79]:
vector[tf.argmin(vector)]

<tf.Tensor: shape=(), dtype=int64, numpy=5>

## Squeezing a tensor ( removing all single dimensions )

In [80]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=(1,1,1,1,50))

In [81]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [82]:
tensor_squeezed = tf.squeeze(tensor)
tensor_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One hot encoding

In [83]:
indices = [0, 1, 2, 3]

In [84]:
tf.one_hot(indices, depth=4), tf.one_hot(indices, depth=5)

(<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], dtype=float32)>)

In [85]:
tf.one_hot(indices, depth=4, on_value=1, off_value=2)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 2, 2],
       [2, 1, 2, 2],
       [2, 2, 1, 2],
       [2, 2, 2, 1]], dtype=int32)>

## Squaring, log, square root

>*`tf.square()` - get the square of every value in a tensor.<br>
>*`tf.sqrt()` - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).<br>
>*`tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).

In [86]:
tensor = tf.range(1, 10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [87]:
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [88]:
tf.sqrt(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [89]:
tf.math.log(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [90]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [91]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [92]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [94]:
# indexing using numpy
J.numpy(), J.numpy()[0]

(array([ 3.,  7., 10.]), 3.0)

By default tensors have `dtype=float32`, where as NumPy arrays have `dtype=float64`.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [95]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Using `@tf.function`

In your TensorFlow adventures, you might come across Python functions which have the decorator [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function).

In the `@tf.function` decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with `@tf.function`, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the [Better performnace with tf.function](https://www.tensorflow.org/guide/function) guide.

In [96]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [97]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>